/*
* generated by Xtext
*/
package compil.dslcalculette.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DCalcAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("compil/dslcalculette/parser/antlr/internal/InternalDCalc.tokens");
	}
}
