/*
* generated by Xtext
*/
package compil.dslcalculette.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import compil.dslcalculette.services.DCalcGrammarAccess;

public class DCalcParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DCalcGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected compil.dslcalculette.parser.antlr.internal.InternalDCalcParser createParser(XtextTokenStream stream) {
		return new compil.dslcalculette.parser.antlr.internal.InternalDCalcParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DCalcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DCalcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
