/*
 * generated by Xtext
 */
package compil.dslcalculette.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDCalcValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(compil.dslcalculette.dCalc.DCalcPackage.eINSTANCE);
		return result;
	}
}
