/*
 * generated by Xtext
 */
package compil.dslcalculette;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DCalcRuntimeModule extends compil.dslcalculette.AbstractDCalcRuntimeModule {

}
