/*
* generated by Xtext
*/
package compil.dslcalculette;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DCalcStandaloneSetup extends DCalcStandaloneSetupGenerated{

	public static void doSetup() {
		new DCalcStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

