/*
* generated by Xtext
*/
package compil.dslcalculette;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DCalcUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return compil.dslcalculette.ui.internal.DCalcActivator.getInstance().getInjector("compil.dslcalculette.DCalc");
	}
	
}
