grammar fr.univLille1.compil.calculette.Calculette with org.eclipse.xtext.common.Terminals

generate calculette "http://www.univLille1.fr/compil/calculette/Calculette"

Calculette:
	(calculs+=Calc '\n')*;

Calc: e=Expr;

Expr:
	Term ({Expr.left=current} op=('+'|'-') right=Expr)?;

Term returns Expr:
	Factor ({Expr.left=current} op=('*'|'/') right=Term)?;

Factor returns Expr:
	'(' Expr ')'
	| {Number} (neg ?= '-')? value=INT /* ('.' frac=INT)? ('e' (negexp ?= '-')? exponent=INT)? */
;