/*
 * generated by Xtext
 */
package compil.dslcalculette.ui.contentassist

import compil.dslcalculette.ui.contentassist.AbstractDCalcProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DCalcProposalProvider extends AbstractDCalcProposalProvider {
}
