/*
 * generated by Xtext
 */
package compil.dslcalculette.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DCalcUiModule extends compil.dslcalculette.ui.AbstractDCalcUiModule {
	public DCalcUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
