/*
 * generated by Xtext
 */
package compil.dslcalculette.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import compil.dslcalculette.ui.internal.DCalcActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DCalcExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DCalcActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DCalcActivator.getInstance().getInjector(DCalcActivator.COMPIL_DSLCALCULETTE_DCALC);
	}
	
}
